export {default as Navbar} from './header/Navbar';
export {default as Header} from './header/Header';
export {default as Body} from './body/Body';
export {default as Footer} from './footer/Footer';
export {default as Audience } from './body/sections/roadMap/Audience';
export {default as ConnectionWithInnovationCenter } from './body/sections/eventIntro/ConnectionWithInnovationCenter';
export {default as EventIntro} from './body/sections/eventIntro/EventIntro';
export {default as Guidance} from './body/sections/Guidance';
export {default as NecessityOfEvent} from './body/sections/eventIntro/NecessityOfEvent';
export {default as ParticipationForm} from './body/sections/participationForm/ParticipationForm';
export {default as RoadMap} from './body/sections/roadMap/RoadMap';
export {default as Specialized} from './body/sections/specialized/Specialized';
export {default as Supporters} from './body/sections/Supporters';
export {default as Faq} from './body/sections/FAQ/Faq';
export {default as ParticipantRegistration} from './Registrations/participantRegistration/ParticipantRegistration';
export {default as Spinner} from '../components/Spinner';
export {default as AllUsers} from './users/AllUsers';